runtime: python37
service: api

env_variables:
  DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
  DISCORD_GUILD_ID: $DISCORD_GUILD_ID
  
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
