version: 2
jobs:
  frontend:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm --prefix frontend install
      - run:
          name: run tests
          command: npm --prefix frontend test
  backend:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: install dependencies
          command: python -m pip install flask pytest
      - run:
          name: run tests
          command: |
            cd backend
            pytest

workflows:
  version: 2
  test:
    jobs:
      - frontend
      - backend
