version: 2
jobs:
  frontend:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm --prefix frontend install
      - run:
          name: run tests
          command: npm --prefix frontend test
      - run:
          name: build
          command: npm --prefix frontend run-script build
      - run:
          name: install persist_to_workspace dependencies
          command: apk add --update ca-certificates openssl && update-ca-certificates
      - persist_to_workspace:
          root: .
          paths:
            - frontend/build
            - frontend/app.yaml
            - backend

  backend:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: install dependencies
          command: python -m pip install flask pytest
      - run:
          name: run tests
          command: |
            cd backend
            pytest
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: deploy to gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet app deploy backend/app.yaml frontend/app.yaml --project cadgroupa
            
workflows:
  version: 2
  build_deploy:
    jobs:
      - frontend
      - backend
      - deploy:
          requires:
            - frontend
            - backend
          filters:
            branches:
              only:
                - master
                - circleci
